### ISSUE TITLE
Use K8s DNS Service name for endpoint in Appsettings.json instead of IP address

### ISSUE THREAD

**Issue by nakfour** [Project-MONAI/monai-deploy-informatics-gateway#110]
**Is your feature request related to a problem? Please describe.**
The problem with IP address is that it renders K8s horizontal scaling mute. We would like to make sure all services that provide an endpoint such as RabbitMQ Cluster and MinIO tenants are scalable and services can scale up and down. If IG only goes to the IP address that limits which pod it goes to. 

**Describe the solution you'd like**
endpoint field in appsettings.yaml should be in the form of <my-svc.my-namespace.svc.cluster-domain.example> as described in [K8s documentation.](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)

cc @mocsharp

**Comment by mocsharp** [comment]
IG supports connecting to external services via host names.  The only exception is when the SCP service validates the external application entity's IP Address.

Do you see any issues? Please ensure that the host (or within the container) can resolve the host name.

**Comment by mocsharp** [comment]
Closing as it is already supported
