### ISSUE TITLE
Update projects using monai-deploy as example

### ISSUE THREAD

**Issue by dbericat** [Project-MONAI/monai-deploy-informatics-gateway#18]
Please add Backlog with columns as in https://github.com/Project-MONAI/monai-deploy/projects/2

Please follow same naming convention v0.1.0 as in https://github.com/Project-MONAI/monai-deploy/projects

Please add column Overview as in https://github.com/Project-MONAI/monai-deploy/projects/3

**Comment by mocsharp** [comment]
@dbericat added *User* & *Release Assets*.

**Comment by dbericat** [comment]
LGTM.
