### ISSUE TITLE
Enable logging to ECS

### ISSUE THREAD

**Issue by mocsharp** [Project-MONAI/monai-deploy-informatics-gateway#181]
**Is your feature request related to a problem? Please describe.**

To aggregate logs from all MONAI Deploy services, MIG shall provide a mechanism to deliver logs to external services.

**Describe the solution you'd like**

An option to deliver logs to ECS

**Comment by dbericat** [comment]
ECS as in https://aws.amazon.com/ecs/?

Or https://aws.amazon.com/cloudwatch/?nc2=h_ql_prod_mg_cw that is used on https://aws.amazon.com/solutions/implementations/centralized-logging/?

Or something like ELK? https://www.elastic.co/what-is/elk-stack

**Comment by dbericat** [comment]
@nakfour ^^

**Comment by mocsharp** [comment]
Elasticsearch-Logstash-Kibana (ELK) stack; AWS LogStash for AIDE. 

We will need a way to deliver logs to some HTTP endpoint.  It's just a plug-in that we need to find; there's a already a PR working using Serilog, but it brings in too many .NET Core 2.x dependencies. Therefore, we are looking for another.
