### ISSUE TITLE
MIG to create the bucket on start up

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-informatics-gateway#221]
**Is your feature request related to a problem? Please describe.**
Currently the bucket in Minio is created manually, after speaking to a Trust, they would prefer if this was done automatically to reduce the amount of configuration and training required of them.

**Describe the solution you'd like**
- MIG to create a bucket based on the appsettings.json on startup
- MIG to go into a failure loop if it cannot connect to MinIO on startup

**Describe alternatives you've considered**
- Manually creation. This is fine for the initial deployments but as we scale out it seems better to have this done automatically

**Additional context**
- To be done the same way we create queues and collections in Rabbit and Mongo

**Comment by mocsharp** [comment]
Close as fixed
