### ISSUE TITLE
Enable workflow triggering with a patient, a study or a series

### ISSUE THREAD

**Issue by mocsharp** [Project-MONAI/monai-deploy-informatics-gateway#26]
**Is your feature request related to a problem? Please describe.**
There may be times when DICOM data is received in bulk containing multiple patients, studies, and series.  However, oftentimes, a model may be designed only for a study or a series.  Therefore, MIG must be able to sort and group the incoming data and trigger based on the user's configuration.

**Describe the solution you'd like**
Allow users to group data and submit them by patient, study, or series for DICOM files.  
If grouping is set to study and 3 studies are received, then 3 jobs are triggered.

**Describe alternatives you've considered**
The other option is to have Workflow Manager handle the data grouping.

**Comment by mocsharp** [comment]
cc @joshliberty

**Comment by joshliberty** [comment]
How is this controlled? Is it a global configuration setting, or per originating AE title, or something else entirely?

**Comment by mocsharp** [comment]
> How is this controlled? Is it a global configuration setting, or per originating AE title, or something else entirely?

It is per AE Title; each AE Title can be configured to be grouped by a DICOM tag, preferably by PatientID, StudyInstanceUID, or SeriesInstanceUID.

**Comment by JHancox** [comment]
Might there be a need to regroup the separate jobs back into a single DICOM output? If so, would the MIG also do this or, as you suggested, would it perhaps make sense to have a workflow operator that does the splitting and the recombining?

**Comment by mocsharp** [comment]
@JHancox do you have a use-case for the need to regroup jobs?
One option is to group by "patient" so all DICOM studies belonging to the same patient are assigned to a single workflow. Then let the workflow definition manage what models to run and how to aggregate the results.

**Comment by hshuaib90** [comment]
> It is per AE Title; each AE Title can be configured to be grouped by a DICOM tag, preferably by PatientID, StudyInstanceUID, or SeriesInstanceUID.

What is the rationale here? it is not clear to me why the grouping strategy would be linked to AE Title (assuming you mean AET of origin).

I think it makes most sense for WM rather than MIG to be responsible for grouping patients, studies, series.

**Comment by mocsharp** [comment]
@hshuaib90 The original design was to have the Workflow Manager do the grouping.  However, after redesigned of the Workload Manager, the working group wanted to have it done as part of the gateway.  

It is per AE Title configured on the gateway.  Given the default configuration, group by study, if 10 studies were sent to IG, 10 workflow jobs are triggered.

**Comment by JHancox** [comment]
> @JHancox do you have a use-case for the need to regroup jobs? One option is to group by "patient" so all DICOM studies belonging to the same patient are assigned to a single workflow. Then let the workflow definition manage what models to run and how to aggregate the results.

I don't - but I'm wondering whether @hshuaib90 or others might comment on the likely need to recombine data that has been split by the IG into separate jobs  - and, if so, whether this requirement still suggests that IG is the best place to handle this sort of splitting/re-merging.

**Comment by hshuaib90** [comment]
I think the need to recombine data higher than single study level needs a little more exploration. It definitely is required, for example, for longitudinal results i.e. change of tumour size over time. However, this is commonly implemented as a fetch of the historical exam after receiving the current exam. 

The alternative would be to expect users to manually send multiple studies within a certain time frame to the IG. I'm not a fan of this second workflow as it means no work is done until a radiologist sits down to report or for someone else (e.g. a radiographer/technician) to specifically add this to their list of duties.

In the former scenario, the question of which component out of the IG and WM is responsible for recognising a historic study/series needs to be fetched is key. In my mind, it only makes sense for this to be the WM and the IG would simply perform the fetch.
