### ISSUE TITLE
Collect Requirements to make IG compatible with other MONAI projects

### ISSUE THREAD

**Issue by mocsharp** [Project-MONAI/monai-deploy-informatics-gateway#30]
**Is your feature request related to a problem? Please describe.**
There are other projects in the MONAI community that consume DICOM data but do not currently have a DICOM listener that is compatible.

**Describe the solution you'd like**
Provide an extensible architecture in the current IG design so other MONAI projects may reuse IG to accept DICOM instances over DIMSE plus other protocols.

**Comment by dbericat** [comment]
@pdogra89 @ericspod @aihsani @wyli we are kicking this off as a placeholder for that common DICOM layer we always talk about.

We could not find anything on MONAI Core. If there is any issue, PR or discussion, please link?

**Comment by wyli** [comment]
From the core codebase, We've been discussing this at a high level with the IO working group, and an initial proposal was released here https://github.com/Project-MONAI/MONAI/issues/856.

Then we've [made good progress](https://github.com/Project-MONAI/MONAI/issues/909) towards this by implementing a loader/reader with various backends: https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/image_reader.py. This is preliminary work addressing the input/reader part.

Now we also start to tackle the output/writer part https://github.com/Project-MONAI/MONAI/issues/2620 and details are under design and discussion https://github.com/Project-MONAI/MONAI/pull/3443.

**Comment by mocsharp** [comment]
@wyli FYI - the Informatics Gateway is not a DICOM reader/writer but a service to ingest/export DICOM objects, FHIR resources, and others directly from PACS, EMR systems.

**Comment by mocsharp** [comment]
@dbericat it all depends on how other projects are used in a production environment; if there is a need to ingest DICOM data from external systems.

**Comment by dbericat** [comment]
@ericspod @vikashg @MMelQin related to today's discussion.

**Comment by mocsharp** [comment]
Closing; please reopen when we have detailed requirements
